// <auto-generated />
using System;
using ConsoleApp1.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(BelegContext))]
    [Migration("20231207105630_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ConsoleApp1.models.Artikel", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BelegId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikelId");

                    b.HasIndex("BelegId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("ConsoleApp1.models.Beleg", b =>
                {
                    b.Property<int>("BelegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.HasKey("BelegId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Belege");
                });

            modelBuilder.Entity("ConsoleApp1.models.Benutzer", b =>
                {
                    b.Property<int>("BenutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BenutzerId");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("ConsoleApp1.models.Artikel", b =>
                {
                    b.HasOne("ConsoleApp1.models.Beleg", "Beleg")
                        .WithMany("Artikel")
                        .HasForeignKey("BelegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beleg");
                });

            modelBuilder.Entity("ConsoleApp1.models.Beleg", b =>
                {
                    b.HasOne("ConsoleApp1.models.Benutzer", "Benutzer")
                        .WithMany("Belege")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("ConsoleApp1.models.Beleg", b =>
                {
                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("ConsoleApp1.models.Benutzer", b =>
                {
                    b.Navigation("Belege");
                });
#pragma warning restore 612, 618
        }
    }
}
